services:
  - type: web
    name: hairsaloon
    runtime: node
    plan: free
    buildCommand: |
      npm install &&
      npm run build &&
      echo "Build completed. Checking dist directory:" &&
      ls -la dist/ &&
      ls -la dist/spa/ &&
      ls -la dist/server/
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://hairsaloon-yojh.onrender.com
      - key: VITE_APP_ENV
        value: production
      - key: PING_MESSAGE
        value: "ping pong"
    healthCheckPath: /health
    autoDeploy: false
