services:
  - type: web
    name: hairsaloon
    runtime: node
    plan: free
    buildCommand: |
      rm -rf node_modules package-lock.json
      npm cache clean --force
      npm install --include=optional --verbose
      # Try SWC build first, fallback to Babel if it fails
      npm run build || (
        echo "SWC build failed, trying Babel fallback..." &&
        cp vite.config.fallback.ts vite.config.ts &&
        npm run build
      )
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://hairsaloon-yojh.onrender.com
      - key: VITE_APP_ENV
        value: production
      - key: PING_MESSAGE
        value: "ping pong"
    healthCheckPath: /health
    autoDeploy: false
